# Generated by Django 3.1.1 on 2020-09-06 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255, verbose_name='Nome da Etiqueta')),
                ('Count', models.IntegerField(default=0, verbose_name='No. de utilizações')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255, verbose_name='Nome da Tarefa')),
            ],
            options={
                'verbose_name': 'Lista de Tarefa',
                'verbose_name_plural': 'Lista de Tarefas',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255, verbose_name='Título')),
                ('Notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('Priority', models.IntegerField(verbose_name='Prioridade')),
                ('RemindMeOn', models.DateField(verbose_name='Lembrar em')),
                ('ActivityType', models.CharField(choices=[('indoors', 'indoors'), ('outdoors', 'outdoors')], max_length=50, verbose_name='Tipo de Atividade')),
                ('Status', models.CharField(choices=[('open', 'open'), ('done', 'done')], max_length=50, verbose_name='Status')),
                ('Tags', models.ManyToManyField(to='taskList.Tag')),
                ('TaskList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskList.tasklist')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTaskList',
            fields=[
                ('Id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('Name', models.CharField(max_length=255, verbose_name='Nome da Tarefa')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Lista de Tarefa',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTask',
            fields=[
                ('Id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('Title', models.CharField(max_length=255, verbose_name='Título')),
                ('Notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('Priority', models.IntegerField(verbose_name='Prioridade')),
                ('RemindMeOn', models.DateField(verbose_name='Lembrar em')),
                ('ActivityType', models.CharField(choices=[('indoors', 'indoors'), ('outdoors', 'outdoors')], max_length=50, verbose_name='Tipo de Atividade')),
                ('Status', models.CharField(choices=[('open', 'open'), ('done', 'done')], max_length=50, verbose_name='Status')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('TaskList', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='taskList.tasklist')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tarefa',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTag',
            fields=[
                ('Id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('Name', models.CharField(max_length=255, verbose_name='Nome da Etiqueta')),
                ('Count', models.IntegerField(default=0, verbose_name='No. de utilizações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Etiqueta',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
