# Generated by Django 3.1.1 on 2020-09-07 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskList', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltag',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tag'},
        ),
        migrations.AlterModelOptions(
            name='historicaltask',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical task'},
        ),
        migrations.AlterModelOptions(
            name='historicaltasklist',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical task list'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tasklist',
            options={},
        ),
    ]
